<a href="https://colab.research.google.com/github/hamsika04/6thSem-ML-Lab/blob/main/1BM22CS054_Decision_Tree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

# Load the IRIS dataset
iris_data = pd.read_csv("iris.csv")
X_iris = iris_data.iloc[:, :-1]  # Features
y_iris = iris_data.iloc[:, -1]   # Target

# Split dataset (80% training, 20% testing)
X_train_iris, X_test_iris, y_train_iris, y_test_iris = train_test_split(X_iris, y_iris, test_size=0.2, random_state=42)

# Build and train Decision Tree classifier for IRIS dataset
iris_classifier = DecisionTreeClassifier()
iris_classifier.fit(X_train_iris, y_train_iris)

# Predict and evaluate IRIS model
y_pred_iris = iris_classifier.predict(X_test_iris)
print("IRIS Dataset Accuracy:", accuracy_score(y_test_iris, y_pred_iris))
print("IRIS Dataset Confusion Matrix:\n", confusion_matrix(y_test_iris, y_pred_iris))


IRIS Dataset Accuracy: 1.0
IRIS Dataset Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]


In [ ]:
from sklearn.preprocessing import LabelEncoder

# Load the Drug dataset
drug_data = pd.read_csv("drug.csv")

# Encode categorical features
label_encoders = {}
for column in drug_data.columns[:-1]:  # Exclude target column
    if drug_data[column].dtype == 'object':  # Check if the column is categorical
        le = LabelEncoder()
        drug_data[column] = le.fit_transform(drug_data[column])
        label_encoders[column] = le  # Store encoder for future reference

# Features and target
X_drug = drug_data.iloc[:, :-1]
y_drug = drug_data.iloc[:, -1]

# Split dataset (80% training, 20% testing)
X_train_drug, X_test_drug, y_train_drug, y_test_drug = train_test_split(X_drug, y_drug, test_size=0.2, random_state=42)

# Build and train Decision Tree classifier for Drug dataset
drug_classifier = DecisionTreeClassifier()
drug_classifier.fit(X_train_drug, y_train_drug)

# Predict and evaluate Drug model
y_pred_drug = drug_classifier.predict(X_test_drug)
print("Drug Dataset Accuracy:", accuracy_score(y_test_drug, y_pred_drug))
print("Drug Dataset Confusion Matrix:\n", confusion_matrix(y_test_drug, y_pred_drug))


Drug Dataset Accuracy: 1.0
Drug Dataset Confusion Matrix:
 [[ 6  0  0  0  0]
 [ 0  3  0  0  0]
 [ 0  0  5  0  0]
 [ 0  0  0 11  0]
 [ 0  0  0  0 15]]


In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error

# Load the Petrol Consumption dataset
petrol_data = pd.read_csv("petrol_consumption.csv")
X_petrol = petrol_data.iloc[:, :-1]  # Features
y_petrol = petrol_data.iloc[:, -1]   # Target

# Split dataset (80% training, 20% testing)
X_train_petrol, X_test_petrol, y_train_petrol, y_test_petrol = train_test_split(X_petrol, y_petrol, test_size=0.2, random_state=42)

# Build and train Regression Tree for Petrol Consumption
petrol_regressor = DecisionTreeRegressor()
petrol_regressor.fit(X_train_petrol, y_train_petrol)

# Predict and evaluate Petrol model
y_pred_petrol = petrol_regressor.predict(X_test_petrol)
print("Mean Absolute Error:", mean_absolute_error(y_test_petrol, y_pred_petrol))
print("Mean Squared Error:", mean_squared_error(y_test_petrol, y_pred_petrol))
print("Root Mean Squared Error:", np.sqrt(mean_squared_error(y_test_petrol, y_pred_petrol)))


Mean Absolute Error: 86.5
Mean Squared Error: 15607.7
Root Mean Squared Error: 124.9307808348287
